# Generated by Django 5.2.6 on 2025-10-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='feeder_name',
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('low_food', 'Nível Baixo de Ração'), ('maintenance', 'Manutenção Necessária'), ('error', 'Erro no Sistema'), ('offline', 'Equipamento Offline')], max_length=20),
        ),
    ]
