# Generated by Django 5.2.6 on 2025-10-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inteligente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_id',
        ),
    ]
