# Generated by Django 5.2.6 on 2025-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligente', '0002_alter_alert_options_remove_alert_feeder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Manutenção'),
        ),
    ]
