# Generated by Django 5.2 on 2025-10-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligente', '0003_userprofile_created_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_executive_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo Executivo Personalizado'),
        ),
    ]
