# Generated by Django 5.2 on 2025-11-15 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligente', '0004_userprofile_custom_executive_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('kg_consumed', models.FloatField(default=0.0)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_consumptions', to='inteligente.feeder')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('feeder', 'year', 'month')},
            },
        ),
    ]
