# Generated by Django 5.2.6 on 2025-11-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligente', '0005_monthlyconsumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Capacidade (kg)'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='daily_consumption',
            field=models.FloatField(default=0, verbose_name='Consumo Diário (kg)'),
        ),
    ]
