# Generated by Django 5.2 on 2025-12-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligente', '0007_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinglog',
            name='feeder_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Nível do Alimentador (%)'),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='received_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem Recebida'),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Remetente'),
        ),
    ]
